version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80" 
    depends_on:
      - fileconverterapi

  fileconverterapi:
    build: ./backend
    ports:
      - "8080:8080"
    expose:
      - "8081"